### PR TITLE
can be used as a reporting plugin

### PR DESCRIPTION
**Pull request by hrotkogabor**
Add the ability to use gitlog plugin as a reporting plugin, including it in a generated site.
I also had to rename the output to gitlog, as changelog reporting plugin already exists.

### CODE REVIEW

**Comment by danielflower** [comment]
That's a very useful feature. Can you just put the default filenames back to `changelog.txt` etc? Otherwise this is a breaking change for people assuming filename patterns. Thanks for the contribution.

**Comment by hrotkogabor** [comment]
done

**Comment by danielflower** [comment]
Thanks again, this has been released in 1.11.0

But I'm trying to use it to generate a maven site report for the plugin itself. Stupid question, but how do you actually use it? I've added the following to the reporting plugins:

	<plugin>
		<groupId>com.github.danielflower.mavenplugins</groupId>
		<artifactId>gitlog-maven-plugin</artifactId>
		<version>1.11.0</version>
		<configuration>
			<simpleHTMLChangeLogFilename>gitlog.html</simpleHTMLChangeLogFilename>
		</configuration>
	</plugin>

Output says:

	[INFO] <<< maven-surefire-report-plugin:2.18.1:report < [surefire]test @ gitlog-maven-plugin <<<
	[INFO] configuring report plugin com.github.danielflower.mavenplugins:gitlog-maven-plugin:1.11.0
	[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:2.8
	[INFO] Relativizing decoration links with respect to project URL: http://github.com/danielflower/maven-gitlog-plugin
	[INFO] Rendering site with org.apache.maven.skins:maven-fluido-skin:jar:1.3.0 skin.
	[INFO] Skipped "Surefire Report" report (maven-surefire-report-plugin:2.18.1:report-only), file "surefire-report.html" already exists for the English version.
	[INFO] Rendering 2 Doxia documents: 2 markdown
	[INFO] Generating "Plugin Documentation" report --- maven-plugin-plugin:3.4:report
	[WARNING]

	Goal prefix is specified as: 'gitlog'. Maven currently expects it to be 'gitlog'.

	[INFO] Mojo extractor with id: java-javadoc found 0 mojo descriptors.
	[INFO] Mojo extractor with id: java-annotations found 3 mojo descriptors.
	[INFO] Generating "Surefire Report" report      --- maven-surefire-report-plugin:2.18.1:report
	[WARNING] Unable to locate Test Source XRef to link to - DISABLED
	[INFO] Generating "Project Team" report         --- maven-project-info-reports-plugin:2.8:project-team
	[INFO] Generating "Continuous Integration" report --- maven-project-info-reports-plugin:2.8:cim
	[INFO] Generating "Issue Tracking" report       --- maven-project-info-reports-plugin:2.8:issue-tracking
	[INFO] Generating "Project License" report      --- maven-project-info-reports-plugin:2.8:license
	[INFO] Generating "Source Repository" report    --- maven-project-info-reports-plugin:2.8:scm
	[INFO] Rendering 3 generated Doxia documents: 3 xdoc
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD SUCCESS
	[INFO] ------------------------------------------------------------------------

...but there is no file generated. I'm probably missing something really simple.

**Comment by hrotkogabor** [comment]
I finally figured it out.
The problem appears from site plugin 3.4.
The solution is to remove "aggregator = true" from the @Mojo declaration at class GenerateMojo.
Can it be removed, or is it necessary?

**Comment by danielflower** [comment]
Hmm.... I think it needs to be there actually. If not, then it will run the gitlog against every module in a multi-module project. If it's a bug in site plugin 3.4, then maybe there is/will be a fix for it?

**Pull request merged**
