### PR TITLE
able to test custom git dir

### PR DESCRIPTION
**Pull request by hrotkogabor**
Add the ability to test custom git dir.

### CODE REVIEW

**Comment by danielflower** [comment]
Thanks for the change, but looks like github can't automatically merge. Can you update and push merge conflict?

**Comment by hrotkogabor** [comment]
I dont see any conflict, while tried to merge testCustomDir to master on local. How can I solve this?

**Comment by danielflower** [comment]
I just merged manually and pushed. Thanks!

**Comment by danielflower** [comment]
Released in 1.11.0

**Pull request merged**
